services:
  app-v1:
    image: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/secure-app:v5
    container_name: appv1.0-container
    environment:
      - APP_VERSION=v1
      - REDIS_HOST=redis
    ports: 
      - "7001:7000"
    networks: 
      - gateway-network
    depends_on:
      - redis
    restart: always

  app-v2:
    image: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/secure-app:v5
    container_name: appv2.0-container
    environment:
      - APP_VERSION=v2
      - REDIS_HOST=redis
    ports:
      - "7002:7000"
    networks:
      - gateway-network
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:alpine
    container_name: final-proj-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gateway-network
    depends_on:
      - app-v1

  redis:
    image: redis:7-alpine
    container_name: redis-backend
    networks: 
      - gateway-network
    restart: always

networks:
  gateway-network:
    driver: bridge
